// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3vZg0To5wZuFGc8mjtcjj0cyFp34I52Q',
    appId: '1:917999733048:web:fd7f1d1660612c5fd299cd',
    messagingSenderId: '917999733048',
    projectId: 'vital-match-362c8',
    authDomain: 'vital-match-362c8.firebaseapp.com',
    storageBucket: 'vital-match-362c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtceGo14wXpw6X5Q8b5fNkzsTj8_k2RvA',
    appId: '1:917999733048:android:01c27d3169c4905fd299cd',
    messagingSenderId: '917999733048',
    projectId: 'vital-match-362c8',
    storageBucket: 'vital-match-362c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD28IY-wsBR3NaRznj7ubkjR7uTBwWCauk',
    appId: '1:917999733048:ios:74cf5588b9f62bc6d299cd',
    messagingSenderId: '917999733048',
    projectId: 'vital-match-362c8',
    storageBucket: 'vital-match-362c8.firebasestorage.app',
    iosBundleId: 'com.example.vitalMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD28IY-wsBR3NaRznj7ubkjR7uTBwWCauk',
    appId: '1:917999733048:ios:74cf5588b9f62bc6d299cd',
    messagingSenderId: '917999733048',
    projectId: 'vital-match-362c8',
    storageBucket: 'vital-match-362c8.firebasestorage.app',
    iosBundleId: 'com.example.vitalMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3vZg0To5wZuFGc8mjtcjj0cyFp34I52Q',
    appId: '1:917999733048:web:6de625dfe6f9f9f0d299cd',
    messagingSenderId: '917999733048',
    projectId: 'vital-match-362c8',
    authDomain: 'vital-match-362c8.firebaseapp.com',
    storageBucket: 'vital-match-362c8.firebasestorage.app',
  );
}
